### ISSUE TITLE
Upgrade to 0.29

### ISSUE THREAD

**Issue by lizconlan** [mysociety/ipvtheme#38]
## ToDo

- [x] Check overridden templates for `<%= flash[:notice] %>` (see [upgrade branch](https://github.com/mysociety/ipvtheme/tree/upgrade-to-0.29))
- [x] Check template changes
- [x] Check/regenerate theme translations
- [x] Get translations updated
- [x] Test locally
- [x] Merge the upgrade-to-0.29 theme branch

## Deploy to-do list
- [x] Migrate `COOKIE_STORE_SESSION_SECRET` value to `SECRET_KEY_BASE`
- [x] Add `BLOCK_RATE_LIMITED_IPS`, `BLOCK_RESTRICTED_COUNTRY_IPS`, `BLOCK_SPAM_ABOUT_ME_TEXT`, `BLOCK_SPAM_COMMENTS`, `BLOCK_SPAM_EMAIL_DOMAINS`, `BLOCK_SPAM_REQUESTS` and `ENABLE_ANTI_SPAM` config values.
- [x] Deploy
- [x] Run `bundle exec rake temp:cache_delivery_status`
- [x] Run `bundle exec rake db:seed`
- [x] Run `bundle exec rake temp:migrate_admins_and_pros_to_roles`
- [x] Run `bundle exec rake temp:remove_line_breaks_from_request_titles`
- [x] Run `bundle exec rake temp:generate_request_summaries`
- [x] Run `bundle exec rake temp:set_use_notifications`

**Comment by lizconlan** [comment]
I've pulled in the latest theme translations (now showing as 100% translated) and the main translations are up to date with 0.29.0.2

**Comment by lizconlan** [comment]
Should just need a quick check to make sure I've not missed anything then it's good to go

**Comment by garethrees** [comment]
Done
