### ISSUE TITLE
Better support for internal review requests being sent by mail

### ISSUE THREAD

**Issue by crowbot** [mysociety/ipvtheme#6]
- [ ] Additions to text on the ipvtheme page for requesting an internal review - https://github.com/mysociety/ipvtheme/issues/2
- [ ] A custom action to download the text of a request for internal review, ready for printing https://github.com/mysociety/ipvtheme/issues/3
- [ ] An email alert to be sent to the requester 30 days after a request for internal review has been made https://github.com/mysociety/ipvtheme/issues/4
- [ ] Change link in followup template to point to help section on requesting https://github.com/mysociety/ipvtheme/issues/5
- [ ] Markup internal review text for translation
